FROM golang:1.18 as builder

WORKDIR /go/src
COPY . .

ENV PATH="/go/bin:${PATH}"

RUN make build.server

FROM scratch

WORKDIR /app

COPY --from=builder ./go/src/tts-server ./
COPY --from=builder ./go/src/.env ./

ENTRYPOINT ["./tts-server"]
