// Code generated by MockGen. DO NOT EDIT.
// Source: client.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gateway "github.com/EdlanioJ/tts/domain/gateway"
	gomock "github.com/golang/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// GetAudio mocks base method.
func (m *MockClient) GetAudio(arg0 gateway.ClientInput) (gateway.ClientOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAudio", arg0)
	ret0, _ := ret[0].(gateway.ClientOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAudio indicates an expected call of GetAudio.
func (mr *MockClientMockRecorder) GetAudio(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAudio", reflect.TypeOf((*MockClient)(nil).GetAudio), arg0)
}
